"""initial_schema

Revision ID: 1515b123a43a
Revises: 
Create Date: 2026-02-13 00:17:48.132280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1515b123a43a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_tenant_created', 'audit_log', ['tenant_id', 'created_at'], unique=False)
    op.create_table('disclaimer_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_es', sa.Text(), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('fiscal_years',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uvt_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('obligation_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsible_entity', sa.String(length=255), nullable=False),
    sa.Column('legal_base', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('obligation_periodicities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obligation_type_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nit_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.ForeignKeyConstraint(['obligation_type_id'], ['obligation_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obligation_type_id', 'fiscal_year_id', name='uq_obligation_periodicity')
    )
    op.create_table('rule_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_year_id', 'version', name='uq_ruleset_fy_version')
    )
    op.create_table('thresholds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value_uvt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('value_cop', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('legal_reference', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_year_id', 'code', name='uq_thresholds_fy_code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_table('disclaimer_acceptances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('disclaimer_version_id', sa.UUID(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disclaimer_version_id'], ['disclaimer_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('obligation_type_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logic_operator', sa.String(length=5), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('result_if_true', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['obligation_type_id'], ['obligation_types.id'], ),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rules_ruleset_obligation_priority', 'rules', ['rule_set_id', 'obligation_type_id', 'priority'], unique=False)
    op.create_table('tax_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year_id', sa.UUID(), nullable=False),
    sa.Column('persona_type', sa.String(length=30), nullable=False),
    sa.Column('regime', sa.String(length=30), nullable=False),
    sa.Column('is_iva_responsable', sa.Boolean(), nullable=False),
    sa.Column('economic_activity_ciiu', sa.String(length=10), nullable=True),
    sa.Column('economic_activities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingresos_brutos_cop', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('patrimonio_bruto_cop', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('has_employees', sa.Boolean(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('has_rut', sa.Boolean(), nullable=False),
    sa.Column('has_comercio_registration', sa.Boolean(), nullable=False),
    sa.Column('nit_last_digit', sa.Integer(), nullable=True),
    sa.Column('consignaciones_cop', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('compras_consumos_cop', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fiscal_year_id', name='uq_profile_user_fy')
    )
    op.create_index('ix_tax_profiles_tenant', 'tax_profiles', ['tenant_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tax_profile_id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ),
    sa.ForeignKeyConstraint(['tax_profile_id'], ['tax_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('value_secondary', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('obligation_type_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('periodicity', sa.String(length=30), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['obligation_type_id'], ['obligation_types.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calendar_tenant', 'calendar_entries', ['tenant_id'], unique=False)
    op.create_index('ix_calendar_user_due_date', 'calendar_entries', ['user_id', 'due_date'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('obligation_type_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('triggered_rule_id', sa.UUID(), nullable=True),
    sa.Column('conditions_evaluated', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation_es', sa.Text(), nullable=False),
    sa.Column('explanation_en', sa.Text(), nullable=True),
    sa.Column('legal_references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('periodicity', sa.String(length=30), nullable=True),
    sa.Column('responsible_entity', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['obligation_type_id'], ['obligation_types.id'], ),
    sa.ForeignKeyConstraint(['triggered_rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_results')
    op.drop_index('ix_calendar_user_due_date', table_name='calendar_entries')
    op.drop_index('ix_calendar_tenant', table_name='calendar_entries')
    op.drop_table('calendar_entries')
    op.drop_table('rule_conditions')
    op.drop_table('evaluations')
    op.drop_index('ix_tax_profiles_tenant', table_name='tax_profiles')
    op.drop_table('tax_profiles')
    op.drop_index('ix_rules_ruleset_obligation_priority', table_name='rules')
    op.drop_table('rules')
    op.drop_table('disclaimer_acceptances')
    op.drop_table('users')
    op.drop_table('thresholds')
    op.drop_table('rule_sets')
    op.drop_table('obligation_periodicities')
    op.drop_table('tenants')
    op.drop_table('obligation_types')
    op.drop_table('fiscal_years')
    op.drop_table('disclaimer_versions')
    op.drop_index('ix_audit_log_tenant_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
